import armory from "@/assets/stage-armory.jpg";
import camera from "@/assets/stage-camera.jpg";
import vehicles from "@/assets/stage-vehicles.jpg";
import warehouse from "@/assets/hero-wide.jpg";
import type { Category, Client, KpiAnalytics, Prop, RentalBooking } from "./types";

export const mockCategories: Category[] = [
  { id: 1, name: "Armory & Weapons", slug: "weapons", icon: "ShieldAlert" },
  { id: 2, name: "Cinema Cameras & Audio", slug: "camera-audio", icon: "Camera" },
  { id: 3, name: "Vintage Vehicles", slug: "vehicles", icon: "Car" },
  { id: 4, name: "Period & Hero Gadgets", slug: "gadgets", icon: "Laptop" },
  { id: 5, name: "Lighting & Grip", slug: "lighting", icon: "Lightbulb" },
];

const img = { weapons: armory, "camera-audio": camera, vehicles, gadgets: warehouse, lighting: warehouse };

export const mockProps: Prop[] = [
  {
    id: 1,
    serial_number: "SCP-WPN-0001",
    title: "1873 Colt Single Action Revolver (Non-Firing)",
    category_id: 1,
    category_slug: "weapons",
    genre_tags: ["Mass Action", "Retro 80s", "Crime Thriller"],
    daily_rate: 3500,
    weekly_rate: 19500,
    security_deposit: 25000,
    replacement_value: 145000,
    condition_rating: "Distressed/Vintage",
    status: "In-Stock",
    image_urls: [img.weapons],
    description:
      "Screen-accurate aged revolver with functioning hammer and cylinder rotation. Ships with holster and dummy rounds.",
    qr_code_id: "QR-SCP-WPN-0001",
  },
  {
    id: 2,
    serial_number: "SCP-WPN-0014",
    title: "Tactical Assault Vest & Breach Kit",
    category_id: 1,
    category_slug: "weapons",
    genre_tags: ["Mass Action", "Sci-Fi"],
    daily_rate: 2200,
    weekly_rate: 12500,
    security_deposit: 15000,
    replacement_value: 78000,
    condition_rating: "Good",
    status: "On-Set",
    image_urls: [img.weapons],
    description: "Full tactical loadout: plate carrier, radio dummy, flashbangs and breaching ram.",
    qr_code_id: "QR-SCP-WPN-0014",
  },
  {
    id: 3,
    serial_number: "SCP-CAM-0007",
    title: "ARRI Alexa Mini Hero Rig (Dressed)",
    category_id: 2,
    category_slug: "camera-audio",
    genre_tags: ["Crime Thriller", "Sci-Fi"],
    daily_rate: 8500,
    weekly_rate: 48000,
    security_deposit: 60000,
    replacement_value: 950000,
    condition_rating: "Mint",
    status: "In-Stock",
    image_urls: [img["camera-audio"]],
    description: "Non-operational hero camera rig dressed with matte box, follow focus and monitor.",
    qr_code_id: "QR-SCP-CAM-0007",
  },
  {
    id: 4,
    serial_number: "SCP-CAM-0021",
    title: "Vintage Boom Pole & Blimp Mic Set",
    category_id: 2,
    category_slug: "camera-audio",
    genre_tags: ["Retro 80s"],
    daily_rate: 1800,
    weekly_rate: 9800,
    security_deposit: 12000,
    replacement_value: 64000,
    condition_rating: "Good",
    status: "Booked",
    image_urls: [img["camera-audio"]],
    description: "Period-correct sound department dressing for 70s/80s film-set scenes.",
    qr_code_id: "QR-SCP-CAM-0021",
  },
  {
    id: 5,
    serial_number: "SCP-VEH-0003",
    title: "1972 Willys Jeep — Road Ready",
    category_id: 3,
    category_slug: "vehicles",
    genre_tags: ["Mass Action", "Retro 80s"],
    daily_rate: 16500,
    weekly_rate: 92000,
    security_deposit: 150000,
    replacement_value: 1850000,
    condition_rating: "Distressed/Vintage",
    status: "In-Stock",
    image_urls: [img.vehicles],
    description: "Fully drivable period jeep with mud-dress option and interchangeable number plates.",
    qr_code_id: "QR-SCP-VEH-0003",
  },
  {
    id: 6,
    serial_number: "SCP-VEH-0009",
    title: "Retro Muscle Car — Blacked Out Chase Unit",
    category_id: 3,
    category_slug: "vehicles",
    genre_tags: ["Mass Action", "Crime Thriller"],
    daily_rate: 24000,
    weekly_rate: 135000,
    security_deposit: 200000,
    replacement_value: 3200000,
    condition_rating: "Mint",
    status: "On-Set",
    image_urls: [img.vehicles],
    description: "Chase-ready muscle car with camera mount points and stunt driver coordination.",
    qr_code_id: "QR-SCP-VEH-0009",
  },
  {
    id: 7,
    serial_number: "SCP-GDT-0011",
    title: "Hero Hacker Terminal & CRT Wall",
    category_id: 4,
    category_slug: "gadgets",
    genre_tags: ["Sci-Fi", "Crime Thriller"],
    daily_rate: 5400,
    weekly_rate: 29500,
    security_deposit: 35000,
    replacement_value: 260000,
    condition_rating: "Good",
    status: "In-Stock",
    image_urls: [img.gadgets],
    description: "Six-monitor CRT stack with playback graphics, cables and practical glow.",
    qr_code_id: "QR-SCP-GDT-0011",
  },
  {
    id: 8,
    serial_number: "SCP-LGT-0005",
    title: "Tungsten 5K Fresnel & Grip Package",
    category_id: 5,
    category_slug: "lighting",
    genre_tags: ["Retro 80s", "Mass Action"],
    daily_rate: 4200,
    weekly_rate: 23000,
    security_deposit: 28000,
    replacement_value: 340000,
    condition_rating: "Needs Maintenance",
    status: "Maintenance",
    image_urls: [img.lighting],
    description: "Classic tungsten unit with stands, flags and scrims for period-lit interiors.",
    qr_code_id: "QR-SCP-LGT-0005",
  },
];

export const mockClients: Client[] = [
  {
    id: 1,
    production_house: "Vetri Cinemas",
    contact_person: "Karthik R",
    email: "line@vetricinemas.in",
    phone: "+91 98400 11223",
    gst_number: "33AABCV1234C1Z5",
  },
  {
    id: 2,
    production_house: "Neon Reel Studios",
    contact_person: "Aditi Sharma",
    email: "prod@neonreel.co",
    phone: "+91 90031 44556",
  },
  {
    id: 3,
    production_house: "Madras Motion Works",
    contact_person: "Suresh Babu",
    email: "ops@madrasmotion.in",
    phone: "+91 94440 77881",
  },
];

export const mockBookings: RentalBooking[] = [
  {
    id: 1,
    booking_code: "SCP-BK-2451",
    client_id: 1,
    production_house: "Vetri Cinemas",
    start_date: "2026-08-18",
    wrap_date: "2026-08-27",
    items: [
      { prop_id: 5, prop_title: "1972 Willys Jeep", applied_daily_rate: 16500, quantity: 1 },
      { prop_id: 2, prop_title: "Tactical Assault Vest", applied_daily_rate: 2200, quantity: 3 },
    ],
    total_rent: 363000,
    security_deposit: 195000,
    advance_paid: 180000,
    balance_due: 183000,
    deposit_status: "Held",
    rental_status: "On-Set",
  },
  {
    id: 2,
    booking_code: "SCP-BK-2448",
    client_id: 2,
    production_house: "Neon Reel Studios",
    start_date: "2026-08-12",
    wrap_date: "2026-08-15",
    items: [{ prop_id: 3, prop_title: "ARRI Alexa Mini Hero Rig", applied_daily_rate: 8500, quantity: 2 }],
    total_rent: 68000,
    security_deposit: 120000,
    advance_paid: 68000,
    balance_due: 0,
    deposit_status: "Refunded",
    rental_status: "Returned",
  },
  {
    id: 3,
    booking_code: "SCP-BK-2455",
    client_id: 3,
    production_house: "Madras Motion Works",
    start_date: "2026-08-20",
    wrap_date: "2026-09-02",
    items: [{ prop_id: 6, prop_title: "Retro Muscle Car", applied_daily_rate: 24000, quantity: 1 }],
    total_rent: 336000,
    security_deposit: 200000,
    advance_paid: 100000,
    balance_due: 236000,
    deposit_status: "Held",
    rental_status: "Reserved",
  },
  {
    id: 4,
    booking_code: "SCP-BK-2440",
    client_id: 1,
    production_house: "Vetri Cinemas",
    start_date: "2026-08-01",
    wrap_date: "2026-08-09",
    items: [{ prop_id: 1, prop_title: "1873 Colt Revolver", applied_daily_rate: 3500, quantity: 4 }],
    total_rent: 126000,
    security_deposit: 100000,
    advance_paid: 40000,
    balance_due: 86000,
    deposit_status: "Held",
    rental_status: "Overdue",
  },
  {
    id: 5,
    booking_code: "SCP-BK-2432",
    client_id: 2,
    production_house: "Neon Reel Studios",
    start_date: "2026-07-24",
    wrap_date: "2026-07-30",
    items: [{ prop_id: 7, prop_title: "Hero Hacker Terminal", applied_daily_rate: 5400, quantity: 1 }],
    total_rent: 37800,
    security_deposit: 35000,
    advance_paid: 37800,
    balance_due: 0,
    deposit_status: "Partially Refunded",
    rental_status: "Damaged",
  },
];

export const mockKpi: KpiAnalytics = {
  gross_revenue_today: 486500,
  net_profit_today: 318400,
  active_rentals: 7,
  on_set_inventory_value: 5120000,
  warehouse_valuation: 18640000,
  outstanding_balances: 505000,
  held_deposits: 495000,
  revenue_trend: [
    { label: "Mon", revenue: 210000, profit: 128000 },
    { label: "Tue", revenue: 318000, profit: 191000 },
    { label: "Wed", revenue: 264000, profit: 152000 },
    { label: "Thu", revenue: 402000, profit: 268000 },
    { label: "Fri", revenue: 511000, profit: 344000 },
    { label: "Sat", revenue: 486500, profit: 318400 },
    { label: "Sun", revenue: 372000, profit: 240000 },
  ],
};