-- =====================================================================
-- Surya Cine Special Props — complete schema (idempotent)
-- Run against the Surya Supabase project (SQL editor or psql).
-- All app access goes through the trusted server layer (service role);
-- only public catalog tables are readable by anon/authenticated.
-- =====================================================================

CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql SET search_path = public;

-- ---------- catalog ----------
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  icon TEXT NOT NULL DEFAULT 'Boxes',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.godowns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  location_code TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.racks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  godown_id BIGINT NOT NULL REFERENCES public.godowns(id) ON DELETE CASCADE,
  rack_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.props (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_number TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  category_slug TEXT NOT NULL,
  genre_tags TEXT[] NOT NULL DEFAULT '{}',
  daily_rate NUMERIC NOT NULL DEFAULT 0,
  weekly_rate NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  replacement_value NUMERIC NOT NULL DEFAULT 0,
  acquisition_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  condition_rating TEXT NOT NULL DEFAULT 'Good',
  status TEXT NOT NULL DEFAULT 'In-Stock',
  image_urls TEXT[] NOT NULL DEFAULT '{}',
  video_preview_url TEXT,
  description TEXT NOT NULL DEFAULT '',
  description_specs TEXT NOT NULL DEFAULT '',
  qr_code_id TEXT NOT NULL DEFAULT '',
  godown_id BIGINT REFERENCES public.godowns(id) ON DELETE SET NULL,
  rack_id BIGINT REFERENCES public.racks(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- clients, bookings, invoices ----------
CREATE TABLE IF NOT EXISTS public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_house TEXT NOT NULL,
  contact_person TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  gst_number TEXT,
  address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT NOT NULL UNIQUE,
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  production_house TEXT NOT NULL DEFAULT '',
  start_date DATE NOT NULL,
  wrap_date DATE NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_rent NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  advance_paid NUMERIC NOT NULL DEFAULT 0,
  balance_due NUMERIC NOT NULL DEFAULT 0,
  deposit_status TEXT NOT NULL DEFAULT 'Held',
  rental_status TEXT NOT NULL DEFAULT 'Reserved',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT NOT NULL UNIQUE,
  doc_type TEXT NOT NULL DEFAULT 'INVOICE',
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  client_name TEXT NOT NULL DEFAULT '',
  client_phone TEXT NOT NULL DEFAULT '',
  production_house TEXT NOT NULL DEFAULT '',
  shoot_location TEXT,
  shoot_start_date DATE NOT NULL,
  shoot_wrap_date DATE NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC NOT NULL DEFAULT 0,
  discount NUMERIC NOT NULL DEFAULT 0,
  transport_charges NUMERIC NOT NULL DEFAULT 0,
  gst_percent NUMERIC NOT NULL DEFAULT 0,
  gst_amount NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  advance_received NUMERIC NOT NULL DEFAULT 0,
  balance_payable NUMERIC NOT NULL DEFAULT 0,
  payment_status TEXT NOT NULL DEFAULT 'Pending',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.rental_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT NOT NULL UNIQUE,
  client_name TEXT NOT NULL DEFAULT '',
  production_house TEXT NOT NULL DEFAULT '',
  phone_number TEXT NOT NULL DEFAULT '',
  shoot_location TEXT NOT NULL DEFAULT '',
  dispatch_date DATE NOT NULL,
  estimated_return_date DATE NOT NULL,
  actual_return_date DATE,
  estimated_days INTEGER NOT NULL DEFAULT 1,
  actual_days_used INTEGER,
  advance_received NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  estimated_total NUMERIC NOT NULL DEFAULT 0,
  total_final_amount NUMERIC NOT NULL DEFAULT 0,
  balance_payable NUMERIC NOT NULL DEFAULT 0,
  order_status TEXT NOT NULL DEFAULT 'Estimated/On-Set',
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- catalog / custom requests ----------
CREATE TABLE IF NOT EXISTS public.prop_requests (
  id BIGSERIAL PRIMARY KEY,
  request_code TEXT NOT NULL,
  request_type TEXT NOT NULL DEFAULT 'Catalog',
  prop_id BIGINT REFERENCES public.props(id) ON DELETE SET NULL,
  prop_title TEXT NOT NULL DEFAULT '',
  custom_description TEXT NOT NULL DEFAULT '',
  reference_image_urls TEXT[] NOT NULL DEFAULT '{}',
  production_house TEXT NOT NULL DEFAULT '',
  contact_person TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  shoot_location TEXT NOT NULL DEFAULT '',
  shoot_start_date DATE,
  shoot_wrap_date DATE,
  quantity INTEGER NOT NULL DEFAULT 1,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'New',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- client portal ----------
CREATE TABLE IF NOT EXISTS public.client_profiles (
  user_id UUID PRIMARY KEY,
  email TEXT NOT NULL DEFAULT '',
  production_house TEXT NOT NULL DEFAULT '',
  contact_person TEXT NOT NULL DEFAULT '',
  designation TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.production_houses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.quote_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_code TEXT NOT NULL UNIQUE,
  user_id UUID NOT NULL,
  production_house TEXT NOT NULL DEFAULT '',
  production_house_id BIGINT REFERENCES public.production_houses(id) ON DELETE SET NULL,
  movie_name TEXT NOT NULL DEFAULT '',
  contact_person TEXT NOT NULL DEFAULT '',
  client_designation TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  shoot_location TEXT NOT NULL DEFAULT '',
  shoot_start_date DATE NOT NULL,
  estimated_return_date DATE NOT NULL,
  estimated_days INTEGER NOT NULL DEFAULT 1,
  actual_return_date DATE,
  actual_days_used INTEGER,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  estimated_total NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  advance_required NUMERIC NOT NULL DEFAULT 0,
  advance_paid NUMERIC NOT NULL DEFAULT 0,
  final_total NUMERIC NOT NULL DEFAULT 0,
  balance_due NUMERIC NOT NULL DEFAULT 0,
  worker_deployment_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
  production_approved_amount NUMERIC(12,2),
  assigned_staff_id BIGINT,
  assigned_staff_name TEXT,
  status TEXT NOT NULL DEFAULT 'quote_requested',
  payment_reference TEXT,
  payment_proof_path TEXT,
  admin_notes TEXT,
  client_notes TEXT,
  accepted_at TIMESTAMPTZ,
  advance_receipt_no TEXT,
  advance_mode TEXT,
  advance_utr TEXT,
  advance_verified_at TIMESTAMPTZ,
  dispatch_at TIMESTAMPTZ,
  dispatch_vehicle TEXT,
  dispatch_notes TEXT,
  balance_cleared_at TIMESTAMPTZ,
  doc_quotation_no TEXT,
  doc_advance_no TEXT,
  doc_challan_no TEXT,
  doc_invoice_no TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.quote_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id BIGINT NOT NULL REFERENCES public.quote_requests(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  kind TEXT NOT NULL DEFAULT 'advance',
  amount NUMERIC NOT NULL DEFAULT 0,
  reference TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- staff / field operations / finance ----------
CREATE TABLE IF NOT EXISTS public.staff_accounts (
  id BIGSERIAL PRIMARY KEY,
  staff_code TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  staff_role TEXT NOT NULL DEFAULT 'field',
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dispatch_logs (
  id BIGSERIAL PRIMARY KEY,
  quote_id BIGINT,
  quote_code TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT 'dispatch',
  vehicle_number TEXT NOT NULL DEFAULT '',
  photo_path TEXT,
  notes TEXT,
  staff_id BIGINT,
  staff_name TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.damage_reports (
  id BIGSERIAL PRIMARY KEY,
  quote_id BIGINT,
  quote_code TEXT NOT NULL DEFAULT '',
  prop_id BIGINT,
  prop_name TEXT NOT NULL DEFAULT '',
  severity TEXT NOT NULL DEFAULT 'minor',
  description TEXT NOT NULL DEFAULT '',
  photo_path TEXT,
  staff_id BIGINT,
  staff_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.expense_ledger (
  id BIGSERIAL PRIMARY KEY,
  category TEXT NOT NULL DEFAULT 'other',
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  description TEXT NOT NULL DEFAULT '',
  spent_on DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- updated_at triggers ----------
DROP TRIGGER IF EXISTS props_touch ON public.props;
CREATE TRIGGER props_touch BEFORE UPDATE ON public.props FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS bookings_touch ON public.bookings;
CREATE TRIGGER bookings_touch BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS prop_requests_touch ON public.prop_requests;
CREATE TRIGGER prop_requests_touch BEFORE UPDATE ON public.prop_requests FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS rental_orders_touch ON public.rental_orders;
CREATE TRIGGER rental_orders_touch BEFORE UPDATE ON public.rental_orders FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS quote_requests_touch ON public.quote_requests;
CREATE TRIGGER quote_requests_touch BEFORE UPDATE ON public.quote_requests FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS client_profiles_touch ON public.client_profiles;
CREATE TRIGGER client_profiles_touch BEFORE UPDATE ON public.client_profiles FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP TRIGGER IF EXISTS staff_accounts_touch ON public.staff_accounts;
CREATE TRIGGER staff_accounts_touch BEFORE UPDATE ON public.staff_accounts FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ---------- RLS + grants ----------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'categories','godowns','racks','props','clients','bookings','invoices','rental_orders',
    'prop_requests','client_profiles','production_houses','quote_requests','quote_payments',
    'staff_accounts','dispatch_logs','damage_reports','expense_ledger'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM anon, authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
  END LOOP;
END $$;

-- Public catalog reads (anon + authenticated) with matching policies.
GRANT SELECT ON public.categories, public.props, public.godowns, public.racks TO anon, authenticated;
DROP POLICY IF EXISTS "Categories are publicly viewable" ON public.categories;
CREATE POLICY "Categories are publicly viewable" ON public.categories FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Props are publicly viewable" ON public.props;
CREATE POLICY "Props are publicly viewable" ON public.props FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Godowns are publicly viewable" ON public.godowns;
CREATE POLICY "Godowns are publicly viewable" ON public.godowns FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Racks are publicly viewable" ON public.racks;
CREATE POLICY "Racks are publicly viewable" ON public.racks FOR SELECT TO anon, authenticated USING (true);

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- ---------- seed reference data ----------
INSERT INTO public.categories (id, name, slug, icon) VALUES
  (1, 'Armory & Weapons', 'weapons', 'ShieldAlert'),
  (2, 'Cinema Cameras & Audio', 'camera-audio', 'Camera'),
  (3, 'Vintage Vehicles', 'vehicles', 'Car'),
  (4, 'Period & Hero Gadgets', 'gadgets', 'Laptop'),
  (5, 'Lighting & Grip', 'lighting', 'Lightbulb')
ON CONFLICT (slug) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.categories','id'), GREATEST((SELECT MAX(id) FROM public.categories), 1));

INSERT INTO public.godowns (name, location_code) VALUES
  ('Godown 1 (Main Soundstage)', 'GD-01'),
  ('Godown 2 (Vehicles & Heavy Props)', 'GD-02'),
  ('Godown 3 (Armory & Electronics)', 'GD-03')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.racks (godown_id, rack_name)
SELECT g.id, r.rack_name FROM public.godowns g
JOIN (VALUES
  ('GD-01', 'Rack A - Top Shelf'), ('GD-01', 'Rack B - Mid Level'), ('GD-01', 'Rack C - Floor Bay'),
  ('GD-02', 'Bay 1 - Heavy Vehicles'), ('GD-02', 'Bay 2 - Period Sets'), ('GD-02', 'Bay 3 - Metal Frames'),
  ('GD-03', 'Armory Vault Rack A'), ('GD-03', 'Optics Vault Rack B'), ('GD-03', 'Audio Rack C')
) AS r(code, rack_name) ON r.code = g.location_code
WHERE NOT EXISTS (
  SELECT 1 FROM public.racks x WHERE x.godown_id = g.id AND x.rack_name = r.rack_name
);
