CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  icon TEXT NOT NULL DEFAULT 'Boxes',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.categories TO anon, authenticated;
GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categories are publicly viewable" ON public.categories FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.props (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_number TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  category_slug TEXT NOT NULL,
  genre_tags TEXT[] NOT NULL DEFAULT '{}',
  daily_rate NUMERIC NOT NULL DEFAULT 0,
  weekly_rate NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  replacement_value NUMERIC NOT NULL DEFAULT 0,
  condition_rating TEXT NOT NULL DEFAULT 'Good',
  status TEXT NOT NULL DEFAULT 'In-Stock',
  image_urls TEXT[] NOT NULL DEFAULT '{}',
  video_preview_url TEXT,
  description TEXT NOT NULL DEFAULT '',
  qr_code_id TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.props TO anon, authenticated;
GRANT ALL ON public.props TO service_role;
ALTER TABLE public.props ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Props are publicly viewable" ON public.props FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_house TEXT NOT NULL,
  contact_person TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  gst_number TEXT,
  address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.clients TO service_role;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT NOT NULL UNIQUE,
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  production_house TEXT NOT NULL DEFAULT '',
  start_date DATE NOT NULL,
  wrap_date DATE NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_rent NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  advance_paid NUMERIC NOT NULL DEFAULT 0,
  balance_due NUMERIC NOT NULL DEFAULT 0,
  deposit_status TEXT NOT NULL DEFAULT 'Held',
  rental_status TEXT NOT NULL DEFAULT 'Reserved',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.bookings TO service_role;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT NOT NULL UNIQUE,
  doc_type TEXT NOT NULL DEFAULT 'INVOICE',
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  client_name TEXT NOT NULL DEFAULT '',
  client_phone TEXT NOT NULL DEFAULT '',
  production_house TEXT NOT NULL DEFAULT '',
  shoot_location TEXT,
  shoot_start_date DATE NOT NULL,
  shoot_wrap_date DATE NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC NOT NULL DEFAULT 0,
  discount NUMERIC NOT NULL DEFAULT 0,
  transport_charges NUMERIC NOT NULL DEFAULT 0,
  gst_percent NUMERIC NOT NULL DEFAULT 0,
  gst_amount NUMERIC NOT NULL DEFAULT 0,
  security_deposit NUMERIC NOT NULL DEFAULT 0,
  advance_received NUMERIC NOT NULL DEFAULT 0,
  balance_payable NUMERIC NOT NULL DEFAULT 0,
  payment_status TEXT NOT NULL DEFAULT 'Pending',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.invoices TO service_role;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql SET search_path = public;
CREATE TRIGGER props_touch BEFORE UPDATE ON public.props FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER bookings_touch BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

INSERT INTO public.categories (id, name, slug, icon) VALUES
  (1, 'Armory & Weapons', 'weapons', 'ShieldAlert'),
  (2, 'Cinema Cameras & Audio', 'camera-audio', 'Camera'),
  (3, 'Vintage Vehicles', 'vehicles', 'Car'),
  (4, 'Period & Hero Gadgets', 'gadgets', 'Laptop'),
  (5, 'Lighting & Grip', 'lighting', 'Lightbulb');
SELECT setval(pg_get_serial_sequence('public.categories', 'id'), 5);