CREATE TABLE IF NOT EXISTS public.godowns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  location_code text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.godowns TO anon, authenticated;
GRANT ALL ON public.godowns TO service_role;
ALTER TABLE public.godowns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Godowns are publicly viewable" ON public.godowns FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS public.racks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  godown_id bigint NOT NULL REFERENCES public.godowns(id) ON DELETE CASCADE,
  rack_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.racks TO anon, authenticated;
GRANT ALL ON public.racks TO service_role;
ALTER TABLE public.racks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Racks are publicly viewable" ON public.racks FOR SELECT TO anon, authenticated USING (true);

ALTER TABLE public.props
  ADD COLUMN IF NOT EXISTS description_specs text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS godown_id bigint REFERENCES public.godowns(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS rack_id bigint REFERENCES public.racks(id) ON DELETE SET NULL;

ALTER TABLE public.prop_requests
  ADD COLUMN IF NOT EXISTS shoot_location text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS public.rental_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number text NOT NULL UNIQUE,
  client_name text NOT NULL DEFAULT '',
  production_house text NOT NULL DEFAULT '',
  phone_number text NOT NULL DEFAULT '',
  shoot_location text NOT NULL DEFAULT '',
  dispatch_date date NOT NULL,
  estimated_return_date date NOT NULL,
  actual_return_date date,
  estimated_days integer NOT NULL DEFAULT 1,
  actual_days_used integer,
  advance_received numeric NOT NULL DEFAULT 0,
  security_deposit numeric NOT NULL DEFAULT 0,
  estimated_total numeric NOT NULL DEFAULT 0,
  total_final_amount numeric NOT NULL DEFAULT 0,
  balance_payable numeric NOT NULL DEFAULT 0,
  order_status text NOT NULL DEFAULT 'Estimated/On-Set',
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.rental_orders TO service_role;
ALTER TABLE public.rental_orders ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER rental_orders_touch BEFORE UPDATE ON public.rental_orders
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

INSERT INTO public.godowns (name, location_code) VALUES
  ('Godown 1 (Main Soundstage)', 'GD-01'),
  ('Godown 2 (Vehicles & Heavy Props)', 'GD-02'),
  ('Godown 3 (Armory & Electronics)', 'GD-03')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.racks (godown_id, rack_name)
SELECT g.id, r.rack_name FROM public.godowns g
JOIN (VALUES
  ('GD-01', 'Rack A - Top Shelf'), ('GD-01', 'Rack B - Mid Level'), ('GD-01', 'Rack C - Floor Bay'),
  ('GD-02', 'Bay 1 - Heavy Vehicles'), ('GD-02', 'Bay 2 - Period Sets'), ('GD-02', 'Bay 3 - Metal Frames'),
  ('GD-03', 'Armory Vault Rack A'), ('GD-03', 'Optics Vault Rack B'), ('GD-03', 'Audio Rack C')
) AS r(code, rack_name) ON r.code = g.location_code
WHERE NOT EXISTS (
  SELECT 1 FROM public.racks x WHERE x.godown_id = g.id AND x.rack_name = r.rack_name
);